### ISSUE TITLE
Aggregate same ingredients

### ISSUE THREAD

**Issue by fnuttens** [cooklang/cooklang-rs#17]
Hi! Love your project, your markup is pretty neat and there’s already some cool tooling available 😃

Have you considered aggregating ingredients sharing the same label and unit in the list?
Some recipes need the same ingredient at multiple steps and currently the parser will always keep them separate.

For example:

```cook
Whip the @eggs{2} and @sugar{130%g}.

-- […]

Add @sugar{100%g} to the mix.
```

Instead of keeping 2 separate `sugar` ingredients (130 g and 100 g respectively), I would expect the parser to keep a single `sugar` ingredient with a quantity of 230 g.

**Comment by Zheoni** [comment]
Hello. The parser can aggregate ingredients. The default behaviour is not to do it to keep compatibility with other cooklang parsers (specially the original one).

This parser features [some extensions to cooklang](https://github.com/cooklang/cooklang-rs/blob/main/extensions.md) and one of them is to reference other ingredients. When creating the parser, enable the appropiate extenions and then you can aggregate ingredients in 2 ways, choose your favourite:

- Just add `>> [duplicate]: ref` to the top of the file
- Add the reference (`&`) modifier **when reusing** an ingredient, so the second sugar would be `@&sugar{100%g}`

After doing this, the [`ScaledRecipe::group_ingredients`](https://docs.rs/cooklang/latest/cooklang/model/struct.Recipe.html#method.group_ingredients) gives you an aggregated ingredients list.
