### ISSUE TITLE
Multiline steps is not an extension

### ISSUE THREAD

**Issue by SenojLuap** [cooklang/cooklang-rs#23]
By the specification, the functionality described in the 'Multiline Steps' extension is actually how cooklang is specified.

See (https://cooklang.org/docs/spec/#steps) for reference. The example even shows that multiline 'paragraphs' constitute a single step.

**Comment by Zheoni** [comment]
This has been added to the spec recently and the parser has updated to always parse multiline steps. Did we forget to remove it somewhere?

**Comment by dubadub** [comment]
Could be... @SenojLuap where did find the text about 'Multiline Steps' extension?

**Comment by dubadub** [comment]
Closing that issue as it's not clear what's the problem.
