### ISSUE TITLE
Paragraphs are erroneously split into multiple steps

### ISSUE THREAD

**Issue by washtubs** [cooklang/cooklang-rs#26]
According to the spec: "Each paragraph in your recipe file is a cooking step. Separate steps with an empty line."

It provides the following as an example:

```
A step,
the same step.

A different step.
```

Pasting that text in the playground, I expect to see 2 steps but instead see 3:

![screenshot_249](https://github.com/user-attachments/assets/9f49099c-f5e5-4e54-a467-f8578d90f94a)

I also see this behavior in the plugin and CLI, so I figure this is the right place to post it. Not sure if this is where the bug is though.

To throw my 2c in pre-emptively, the spec is wise on this IMHO. A good markup language allows for semantic line feeds, essentially allowing the user to break elements down into atomic thoughts being their own lines which is great for editing and making git history easier to interpret, without effecting the presentation.

EDIT:

I should add my cooklang obsidian version is 0.3.0.

And for cooklangcli version I tried both the main branch and 0.8.0, but looking at it again it looks like neither are using the latest version of this crate which is 0.9

**Comment by Zheoni** [comment]
> Each paragraph in your recipe file is a cooking step. Separate steps with an empty line.

This has been added to the spec recently.

This parser has supported it since the beginning but only in the last version it has been enabled by default. So any aplications that have not been updated in the last couple of weeks will probably use old way of breaking the recipe into steps.

Also, I'm pretty sure neither that playground nor the obsidian plugin use the rust parser.

**Comment by dubadub** [comment]
Yep, just wanted to confirm that the playground you mentioned is based of cooklang-ts parser which is (slowly) being migrated to use wasm https://github.com/cooklang/cooklang-ts/pull/27. You can use other playground https://cooklang.github.io/cooklang-rs/ based on rust parser.

**Comment by washtubs** [comment]
OK, I was using the playground that was linked from the [spec README](https://github.com/cooklang/spec?tab=readme-ov-file#projects-which-use-cooklang) fyi.
