### ISSUE TITLE
parser fails over multiple lines

### ISSUE THREAD

**Issue by silky** [cooklang/cooklang-rs#3]
multi-lines seems to be a feature of this parser

however, if an ingredient spans multiple lines, it fails to parse.

consider:

this:

```
Squeeze all the water from the defroshed @packed fresh spinach{5%cups}. Pulse
the spinach in a #food processor{} to roughly chop.
```

yields:

![image](https://github.com/cooklang/cooklang-rs/assets/129525/5c58a30d-7d4f-4ab7-ac4b-e24971316bd2)

(good)

but this

```
Squeeze all the water from the defroshed @packed fresh
spinach{5%cups}. Pulse
the spinach in a #food
processor{} to roughly chop.
```

yields:

![image](https://github.com/cooklang/cooklang-rs/assets/129525/c0128641-66bb-47f4-96dc-2bf7fb7e99ae)

( bad :( )

note that when referencing an existing ingredient, this becomes a parse error. 

ideally, line breaks would be valid anywhere, or at least between words.

**Comment by Zheoni** [comment]
Now this is intended behaviour. When multiline steps are enabled, lines are joined together, but parsed separately.

This is not ideal, and I have been prototyping a big change in the parser that treats multiline steps as one block, but... let's just say it's not ready yet 😅 .

I will leave this open until I finish that change. I will probably take a couple of weeks, I don't have much time this month.

**Comment by Zheoni** [comment]
Fixed! Will be shipped in the new release 😄
