### ISSUE TITLE
Special Metadata: No support for uppercase and whitespace in tag names

### ISSUE THREAD

**Issue by PixelwarStudio** [cooklang/cooklang-rs#8]
I played a bit around with the special metadata extension (in the playground, 0.12.0) and I noticed two non-working cases that I expected to work.

Cases that didn't work:
- Uppercase tags: `>> tags: Tag`
- Tag with whitespace: `>> tags: tag bla`

I'm not sure if the behavior is intended but if so I think it should be documented because it is not obvious.

**Comment by dubadub** [comment]
@Zheoni do those restrictions are coming from implementation requirements? Ideally I think we should allow users to be as creative as they want to be, I could imagine someone use emoji only for example.

**Comment by Zheoni** [comment]
This comes from the old days where the parser was a part of chef. It's easy to change, just a regex.

So should I change it to split by ',' and allow everything?

**Comment by dubadub** [comment]
Yeah, I think that would be the best, thanks!

**Comment by Zheoni** [comment]
Done, I removed the checks for valid tags and added a way for a user of the library to run a custom validator for any metadata entry so the old behaviour can be replicated.
